version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

add_emoji = true
remove_old_emoji = true

[[emoji]]
import = "target/config/emoji.toml"


# [[custom_groups]]
# name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
# type = "select"
# rule = ["[]DIRECT", ".*"]

[[custom_groups]]
import = "target/config/country.toml"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "target/rules/Global.list"

[[rulesets]]
group = "DIRECT"
ruleset = "target/rules/China.list"

# 1. æ‹¦æˆªå¹¿å‘Šï¼ˆå¯é€‰ï¼Œæç®€æ´¾å¦‚æœä¸åœ¨æ„å¹¿å‘Šå¯åˆ æ­¤æ¡ï¼‰
[[rulesets]]
group = "REJECT"
ruleset = "target/rules/default/AdRule.list"

# 2. å±€åŸŸç½‘ä¸ä¿®æ­£ï¼ˆç¡®ä¿æœ¬åœ°è¿æ¥ä¸èµ°ä»£ç†ï¼‰
[[rulesets]]
group = "DIRECT"
ruleset = "target/rules/default/LocalAreaNetwork.list"

# 3. æ ¸å¿ƒåˆ†æµï¼šæ‰€æœ‰è¢«å¢™çš„å›½å¤–æœåŠ¡ï¼ˆGoogle/Twitter/GitHubç­‰ï¼‰
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "target/rules/default/Global.list"

# 4. å›½å†…ç›´è¿ï¼ˆåŸºäºåŸŸåå’Œåœ°ç†ä½ç½® IPï¼‰
[[rulesets]]
group = "DIRECT"
ruleset = "target/rules/default/China.list"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

# 5. ç»ˆæå…œåº•ï¼šæ²¡è¢«ä¸Šé¢å‘½ä¸­çš„å…¨éƒ¨èµ°ä¸»ç»„
[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]FINAL"